version: '3.10'
services:
  keycloak:
      volumes:
        - ./imports:/opt/jboss/keycloak/imports
      image: quay.io/keycloak/keycloak
      ports:
        - "8080:8080"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command:
        - "-Dkeycloak.migration.action=import"
        - "-Dkeycloak.migration.provider=singleFile"
        - "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json"
        - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
        - start-dev
  db:
    image: postgres:15.2
    restart: always
    container_name: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - service_network
  web:
    container_name: task_service
    build: .
    ports:
      - 8000:80
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    networks:
      - service_network
  web_1:
    container_name: serv_2
    build: app/serv_s
    ports:
      - 8001:80

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - service_network
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - service_network
  grafana:
      image: grafana/grafana
      ports:
        - '3000:3000'
      volumes:
        - grafana-data:/var/lib/grafana
      depends_on:
        - prometheus
        - loki
      networks:
        - service_network
  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    networks:
      - service_network


networks:
  service_network:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:
  grafana-data: