version: '3.10'
services:
  db:
    image: postgres:15.2
    restart: always
    container_name: task_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - service_network
  web:
    container_name: task_service
    build: .
    ports:
      - 8000:80
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    networks:
      - service_network
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - service_network
networks:
  service_network:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:
